version: '3'
volumes:
  db-data:
    external: true
services:
  db:
    image: postgres
    env_file: .env
    container_name: db
    volumes:
      - db-data:/var/lib/postgresql/db-data
  web:
    build: .
    container_name: web
    env_file: .env
    volumes:
      - .:/home/app/justref
    ports:
      - "3000:3000"
    depends_on:
      - db
    #command: rails s -p 3000 -b 0.0.0.0
